spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: usercenter
    password: Aa1411943325
    url: jdbc:mysql://82.156.242.159:3306/user_center?useUnicode=true&useSSL=false&serverTimezone=GMT&characterEncoding=UTF-8
    # session失效时间
  session:
    timeout: 86400


server:
  port: 8081
  servlet:
    context-path: /api